# Generated by Django 5.1.4 on 2024-12-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.AddField(
            model_name='game',
            name='buyers',
            field=models.ManyToManyField(related_name='games', to='task1.buyer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
