# Generated by Django 5.1.4 on 2024-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_remove_game_buyer_game_buyers_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
